- hosts: webserver
  become: yes
  become_method: sudo
  tasks:
    - name: uninstall apache2
      apt: name=apache2 state=absent

    - name: delete index.html 
      file:
        path: /var/www/html/index.html
        state: absent
